### ISSUE TITLE
Improve number of licenses available

### ISSUE THREAD

**Issue by s-celles** [hroncok/license#3]
Hello,

This library need to improve number of licenses available

Just a small comparison
https://github.com/hroncok/license/tree/master/license/templates

https://github.com/benbalter/licensee/tree/master/vendor/choosealicense.com/_licenses (licenses files taken from https://choosealicense.com/ )

Kind regards

```python
In [9]: from license import core

In [10]: core._db
Out[10]: 
{'AGPL-3.0': license.licenses.AGPLv3OnlyLicense,
 'AGPL-3.0+': license.licenses.AGPLv3LaterLicense,
 'BSD-2-Clause': license.licenses.BSD2ClauseLicense,
 'BSD-3-Clause': license.licenses.BSD3ClauseLicense,
 'GPL-2.0': license.licenses.GPLv2OnlyLicense,
 'GPL-2.0+': license.licenses.GPLv2LaterLicense,
 'GPL-3.0': license.licenses.GPLv3OnlyLicense,
 'GPL-3.0+': license.licenses.GPLv3LaterLicense,
 'LGPL-2.1': license.licenses.LGPLv21OnlyLicense,
 'LGPL-2.1+': license.licenses.LGPLv21LaterLicense,
 'LGPL-3.0': license.licenses.LGPLv3OnlyLicense,
 'LGPL-3.0+': license.licenses.LGPLv3LaterLicense,
 'MIT': license.licenses.MITLicense
```

**Comment by hroncok** [comment]
I created the library to solve a problem for me. I only needed a couple. If you want more licenses, I'd merge a pull request. However I don't have a motivation to add more myself, sorry.

**Comment by s-celles** [comment]
Not an issue. I noticed that licensee can be use as a CLI tool so I can use it this way.
Moreover detecting a project license only using LICENSE file is not a great idea. README can help.
Licensee have several "matcher" to detect license.
Sorry for noise
